### PR TITLE
Update to the last versión (1.7.0)

### PR DESCRIPTION
**Pull request by borekon**
Compiled by myself and works like a charm

### CODE REVIEW

**Comment by alfish2000** [comment]
May I ask how you compiled it by yourself?
I would like to do by myself too.
Maybe this repo here is abandoned.
Cryptomator has reached v1.7.3

**Comment by alfish2000** [comment]
Thanks for your answer.
But how did you compile it then?
How did you produce the files listed here https://github.com/portapps/cryptomator-portable/releases with the latest version of Cryptomator?

**Comment by borekon** [comment]
Followed theses steps: https://portapps.io/doc/contribute/#create-your-first-portapp
1. Install dependencies.
2. Do the git clone
3. Modified files
4. Run ant release.
Did it on Debian 11

**Comment by alfish2000** [comment]
Thanks for your step by step instructions.

I got an error (on Windows 10):
`[exec] main.go:2: running "goversioninfo": exec: "goversioninfo": executable file not found in %PATH%`

After adding
`C:\Users\[MYUSERNAME]\go\bin`
to the PATH it finally worked and the packages were generated.

**Pull request closed without merging**
